FORMAT: 1A
HOST: http://polls.apiblueprint.org/
# SHURI-SCHOOL Api
A set of requests and requirements that make up the api.<br>
This is for shuri-School Api platform.
## Authentication
This API uses school Query Parameter for its authentication.<br>
The parameters that are needed to be sent for this type of authentication are as follows:
`token` - API token from shuri admin to authorize request.
# Group Registered School Data 
## School [/admin/school]

### Call Logged in school data[GET /admin/schools/current{?token,id,name,email}]
Getting Resource related to school while entering his credentials and requesting for authentication.
+ Parameters
    + token (`hgf876890iojds87fv9i0v0f897vf90djlvf09e8`)
             **School-token**: You can call school token from ShuriAdmin to login onto shuri-school.
    + id: 124 (required, number) - ID given to school during school registeration in shuri admin.
    + name: `Kagarama High School` - Name of school used when registering school in shuri admin.
    + email: `kagarama@gmail.com`(required, string) - school email used when registering school in shuri admin.
+ Request (application/json)

    + Headers
            
            token:hgf876890iojds87fv9i0v0f897vf90djlvf09e8

+ Response 200 (application/json)
   
        [
            {
                message: "success",
                user: {
                    email: "kagarama@gmail.com",
                    password: "shurikagarama"
                },
                **stayLogged**:true
            }
        ]
+ Response 401 (application/json)

        [
            {
                message: "Access Denied",
                error: "Unauthorized"
            }
        ]
### SCHOOL LOGIN [POST /admin/schools/auth]
Sending Resource related to school while entering his credentials and requesting for login authentication.
+ Request (application/json)

    + Attributes
        + email: "kagarama@gmail.com" (required)
        + password: "shurikagarama" (required)
        + staylogged:true

+ Response 200 (application/json)

        [
            {
                message: "success",
                token: "hgf876890iojds87fv9i0v0f897vf90djlvf09e8"
            }
        ]
+ Response 201 (application/json)

    + Headers

            Location: /admin/schools/auth

+ Response 404 (application/json)

        [
            {
                message: "validation error",
                error: {
                    email: "Email is invalid"||"Email is required"||"Email/Password is incorrect" ||
                    password: "Password is required"||"Email/Password is incorrect"
                }
            }
        ] 

# Group Welcoming User to Regestered School Message

## Welcome to School [/admin/schools/welcome]
This message is displayed for first when registered school is loggedIn on `shuri-school`.

### Call Registered School Name [GET /admin/schools/welcome/user{?name,user_id,school_name}]
Getting Resource related to school name while entering his credentials and requesting for registeration onto shuriAdmin.
+ Parameters
    + name:"Mugabo Luc" ~ Names for user who login on shuri-school whom registered in school platform during registration process.
    + user_id:1 (required,number) ~ ID given to the user during registration process of school platform.
    + school_name:`kagarama High School` ~ Name of school where user is worked. 
+ Request  (application/json)

    + Headers
            
            user_id:1

+ Response 200 (application/json)

    + body
    
            description: "am kagarama high school"
            
+ Response 401 (application/json)

        
        message: "no description for school",
        error: "Unauthorized"
        
### Setting school description [POST /admin/schools]
Resource related to school confrimation of registeration as description.
+ Request (application/json)

    + Attributes
        + description: "hello am karagama high school" (required)
        + Vision: "Better education to all Rwandan's" (required)
        

+ Response 201 (application/json)

    + Headers

            Location: /admin/schools

# Group Classes

##Classes Of School [/school/classes]
This is classes in `shuri-school`.

###Get All Classes [GET /school/classes]
Getting Resource Related to classes.
+ Response 200 (application/json)

        [
            {
                id: "hgf87-6890-iojds87f-v9i0v-0f897vf90-djlvf09e8",
                className: "S5MEG",
                classProfile: "profile_white",
                subject: "Math 2019",
                updatedDate: "August 20",
                teacherName: "Matanya Davis",
                classCode: "@3744"
            },
            {
                id: "hgf87-6890-iojds87-fv9i0v-0f897vf90-djlvf09e8",
                className: "S6PCB",
                classProfile: "profile",
                subject: "Kiny 2019",
                updatedDate: "Sep 20",
                teacherName: "Muhoza tony",
                classCode: "@6678"
            },
        ]

###Get Class Profile [GET /school/students/{?id,name}]
Getting Resource Related to registered class for a class profile.
+ Parameters
    + id:`hgf87-6890-iojds87-fv9i0v-0f897vf90-djlvf09e8` (required,number) ~ID given to Class during classes registration which required for class profile.
    + name:"S6PCB" (required, string) ~ class name which is used as url params.

+ Response 200 (application/json)

        [
            {   This data can be displayed as class header.
                 id: "hgf87-6890-iojds87-fv9i0v-0f897vf90-djlvf09e8",
                name: "S6PCB",
                profile: "profile",
                subject: "Kiny 2019",
                updatedDate: "Sep 20",
                teacherName: "Muhoza tony",
                code: "@6678"
            }
        ]

+ Response 200 (application/json)

        [
            List of class students which are assigned for the selected class
            {
              name: "Muhozi Alex",
              gender: "Male",
              date: "19 year old"
            },
            {
              name: "Shema Fred",
              gender: "Female",
              date: "18 year old"
            },
            {
              name: "Mucyo Allan",
              gender: "Male",
              date: "11 year old"
            }
        ]

###Create Class [POST /school/classes]
Setting Resource related to class during classes registiration.

+ Request (application/json)

    + Attributes
        + name:"S6PCB"(required)
        + code:"@568"(required)
        + profile:"S6PCB.png"(required)
        
+ Response 201 (application/json)

        Location: /admin/schools 

            [
                {
                    message: "success",
                    status: "class created succefully"
                }
            ]

+ Response 400 (application/json)

        [
            {
                message: "validation error",
                error: {
                    name: "name is required"||
                    code: "country is required"||
                    profile: "phoneNumber is required"||
                }
            }
        ];

+ Response 503 (application/json)

        [
            {
                message: "class could not be created",
                error: "Delivery Failure"
            }
        ]

##Companies [/admin/companies]
Getting all Companies from backend it's all description detail's required in order school to trust it.
### Get All Bus Companies [GET /admin/companies]
Resource fetches all the bus companies and displays them
+ Response 200 (application/json)

        [
            {
                id: "001",
                name: "Matunda LTD",
                email: "matunda@gmail.com",
                country: "Rwanda",
                district: "Gasabo",
                sector: "Remera",
                phoneNumber: "0781415878",
                createdAt: "12/09/2018",
                status:"partened",
            },
            {
                id: "002",
                name: "ISHEJA LTD",
                email: "shejaeddy05@gmail.com",
                country: "Rwanda",
                district: "Kicukiro",
                sector: "Kagarama",
                phoneNumber: "072456788",
                createdAt: "01/02/2019",
                status:"Requested"
            },
            {
                id: "003",
                name: "ISHEJA LTD",
                email: "shejaeddy05@gmail.com",
                country: "Rwanda",
                district: "Kicukiro",
                sector: "Kagarama",
                phoneNumber: "072456788",
                createdAt: "01/02/2019",
                status:"none"
            }
        ]
        
### Get Bus Company Profile [GET /company-profile/{?id,name}]
Resource related in reading a company profile for school.

+ Parameters
       + id: `hgf87-6890-iojds87fv9i0v-0f897vf90-djlvf09e8`(required,string) ~ ID of company related to company id given during registration.
       + name: "Matunda LTD"(required,string)~ Name of company related to company name given during registration.

+ Response 200 (application/json)

                {
                   id: "002"(required,string) ~ ID of company related to company id given during registration.
                   name: "Matunda LTD"(required,string)~ Name of company related to company name given during registration.
                   status:"partened"(required,string) ~ Status related company availablity if is neither partened nor Requested then school can make it partner. 
                   buses:"452"(required,number) ~ buses related to total number of buses owened by company.
                   drivers:"100"(required,number) ~ Drivers related to total number of drivers owened by company as employee.
                   connectionCovered:"2000"(required,number) ~ Connection covered by company as work covered by company.
                   Experienced:"5"(required,number) ~ Experienced time of company.
                }

###Make Partner [POST /companies/{?id}]
Sending Resource related to make company as partner.


+ Parameters

    + id:"003",

+ Request (application/json)

    + Attributes
        + select:"i agree with term and condition"(required) ~ if you need to confrim in order to make partnership.
        
+ Response 201 (application/json)

        Location: /companies 

            [
                {
                    message: "success",
                    status: "make partner succefully"
                }
            ]

+ Response 400 (application/json)

        [
            {
                message: "validation error",
                error: {
                    select: "select is required"||
                }
            }
        ];

+ Response 503 (application/json)

        [
            {
                message: "make partner doesn't done",
                error: "Delivery Failure"
            }
        ]

#Group All Members

## School Members Staff

###Get All Members [GET /all-members]
Resource related to school members staff.

+ Response 200 (applicatio/json)

        [
                {
                id:"001",
                name: "Muhoza patrick",
                role: "Teacher",
                created: "12 May 2019",
                gender: "Male",
                nationality: "Burundian",
                phoneNumber: "+26078878780",
                birthDay: "12 july 2018"
                },
                {
                id:"002",
                name: "Mucyo emmy",
                role: "Director of Discipline",
                created: "12 June 2007",
                visited: "22 hours Ago",
                gender: "Female",
                phoneNumber: "+2507883564",
                birthDay: "12 june 2008"
                },
                {
                id:"003",
                name: "Habimana claude",
                role: "Teacher",
                created: "12 July 2009",
                visited: "10 hours Ago",
                gender: "Male",
                nationality: "Canandian",
                birthDay: "12 may 2000"
                }
        ]
###Get Member Profile [GET /all-members/{?id,name}]
Resource related to school staff member profile

+ Parameters
    + id:"002"(required,number) ~ ID of member related to id given during registration,
    + name:"Muhoza patrick"(required, string) ~ Name of  member related to the name given during registration.
    
+ Response 200 (application/json)

            {
                id:"002",
                name: "Mucyo emmy",
                role: "Director of Discipline",
                created: "12 June 2007",
                visited: "22 hours Ago",
                gender: "Female",
                phoneNumber: "+2507883564",
                birthDay: "12 june 2008"
            },